services:
  proxy:
    image: quay.io/panubo/sshd
    ports:
      - "2222:22"
    volumes:
      - "${SSH_PUBLIC_KEY_PATH-~/.ssh/id_rsa.pub}:/etc/authorized_keys/agent:ro"
    environment:
      TCP_FORWARDING: true
      SSH_USERS: "agent:48:48"
    networks:
      - full-internet
      - no-internet

